package capacity

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
)

// FindPartByID is the resolver for the findPartByID field.
func (r *entityResolver) FindPartByID(ctx context.Context, id string) (*Part, error) {
	return &Part{ID: id}, nil
}

// FindRequirementByID is the resolver for the findRequirementByID field.
func (r *entityResolver) FindRequirementByID(ctx context.Context, id string) (*Requirement, error) {
	return &Requirement{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
