// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package capacity

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Attribute struct {
	Name  string   `json:"name"`
	Value *float64 `json:"value,omitempty"`
}

type Connection struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type Part struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Attributes  []*Attribute  `json:"attributes"`
	Parts       []*Part       `json:"parts"`
	Connections []*Connection `json:"connections"`
	Capacity    *float64      `json:"capacity,omitempty"`
	Bottleneck  []*Part       `json:"bottleneck"`
}

func (Part) IsEntity() {}

type Query struct {
}

type Requirement struct {
	ID            string              `json:"id"`
	Quantity      *string             `json:"quantity,omitempty"`
	Comparison    *Comparison         `json:"comparison,omitempty"`
	Limit         *float64            `json:"limit,omitempty"`
	Subject       *Part               `json:"subject,omitempty"`
	VerifiedBy    []*VerificationCase `json:"verifiedBy"`
	Verdict       Verdict             `json:"verdict"`
	VerdictReason string              `json:"verdictReason"`
}

func (Requirement) IsEntity() {}

type VerificationCase struct {
	ID        string  `json:"id"`
	ShortName *string `json:"shortName,omitempty"`
}

func (VerificationCase) IsEntity() {}

type Comparison string

const (
	ComparisonGe Comparison = "GE"
	ComparisonGt Comparison = "GT"
	ComparisonLe Comparison = "LE"
	ComparisonLt Comparison = "LT"
	ComparisonEq Comparison = "EQ"
)

var AllComparison = []Comparison{
	ComparisonGe,
	ComparisonGt,
	ComparisonLe,
	ComparisonLt,
	ComparisonEq,
}

func (e Comparison) IsValid() bool {
	switch e {
	case ComparisonGe, ComparisonGt, ComparisonLe, ComparisonLt, ComparisonEq:
		return true
	}
	return false
}

func (e Comparison) String() string {
	return string(e)
}

func (e *Comparison) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Comparison(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Comparison", str)
	}
	return nil
}

func (e Comparison) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Comparison) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Comparison) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Verdict string

const (
	VerdictPass         Verdict = "PASS"
	VerdictFail         Verdict = "FAIL"
	VerdictInconclusive Verdict = "INCONCLUSIVE"
	VerdictError        Verdict = "ERROR"
)

var AllVerdict = []Verdict{
	VerdictPass,
	VerdictFail,
	VerdictInconclusive,
	VerdictError,
}

func (e Verdict) IsValid() bool {
	switch e {
	case VerdictPass, VerdictFail, VerdictInconclusive, VerdictError:
		return true
	}
	return false
}

func (e Verdict) String() string {
	return string(e)
}

func (e *Verdict) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Verdict(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Verdict", str)
	}
	return nil
}

func (e Verdict) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Verdict) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Verdict) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
