package capacity

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/Roarge/sysml-federation/examples/pipeline/capacity/flow"
)

// Capacity is the resolver for the capacity field.
func (r *partResolver) Capacity(ctx context.Context, obj *Part) (*float64, error) {
	c, _ := flow.Analyse(r.subject(obj))
	return c, nil
}

// Bottleneck is the resolver for the bottleneck field.
func (r *partResolver) Bottleneck(ctx context.Context, obj *Part) ([]*Part, error) {
	_, cut := flow.Analyse(r.subject(obj))
	out := make([]*Part, 0, len(cut))
	for _, id := range cut {
		out = append(out, &Part{ID: id})
	}
	return out, nil
}

// Verdict is the resolver for the verdict field.
func (r *requirementResolver) Verdict(ctx context.Context, obj *Requirement) (Verdict, error) {
	kind, _ := r.verdict(obj)
	return Verdict(kind), nil
}

// VerdictReason is the resolver for the verdictReason field.
func (r *requirementResolver) VerdictReason(ctx context.Context, obj *Requirement) (string, error) {
	_, reason := r.verdict(obj)
	return reason, nil
}

// Part returns PartResolver implementation.
func (r *Resolver) Part() PartResolver { return &partResolver{r} }

// Requirement returns RequirementResolver implementation.
func (r *Resolver) Requirement() RequirementResolver { return &requirementResolver{r} }

type (
	partResolver        struct{ *Resolver }
	requirementResolver struct{ *Resolver }
)
