package projection

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/Roarge/sysml-federation/adapter/model"
)

// FindPartByID is the resolver for the findPartByID field.
func (r *entityResolver) FindPartByID(ctx context.Context, id string) (*model.Part, error) {
	p, ok := partByID(r.current(ctx), id)
	if !ok {
		return nil, fmt.Errorf("%w: part %q", model.ErrNotFound, id)
	}
	return p, nil
}

// FindRequirementByID is the resolver for the findRequirementByID field.
func (r *entityResolver) FindRequirementByID(ctx context.Context, id string) (*model.Requirement, error) {
	req, ok := requirementByID(r.current(ctx), id)
	if !ok {
		return nil, fmt.Errorf("%w: requirement %q", model.ErrNotFound, id)
	}
	return req, nil
}

// FindVerificationCaseByID is the resolver for the findVerificationCaseByID field.
func (r *entityResolver) FindVerificationCaseByID(ctx context.Context, id string) (*model.VerificationCase, error) {
	v, ok := verificationCaseByID(r.current(ctx), id)
	if !ok {
		return nil, fmt.Errorf("%w: verification case %q", model.ErrNotFound, id)
	}
	return v, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
