// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package projection

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type Comparison string

const (
	ComparisonGe Comparison = "GE"
	ComparisonGt Comparison = "GT"
	ComparisonLe Comparison = "LE"
	ComparisonLt Comparison = "LT"
	ComparisonEq Comparison = "EQ"
)

var AllComparison = []Comparison{
	ComparisonGe,
	ComparisonGt,
	ComparisonLe,
	ComparisonLt,
	ComparisonEq,
}

func (e Comparison) IsValid() bool {
	switch e {
	case ComparisonGe, ComparisonGt, ComparisonLe, ComparisonLt, ComparisonEq:
		return true
	}
	return false
}

func (e Comparison) String() string {
	return string(e)
}

func (e *Comparison) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Comparison(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Comparison", str)
	}
	return nil
}

func (e Comparison) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Comparison) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Comparison) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Direction string

const (
	DirectionIn    Direction = "IN"
	DirectionOut   Direction = "OUT"
	DirectionInout Direction = "INOUT"
)

var AllDirection = []Direction{
	DirectionIn,
	DirectionOut,
	DirectionInout,
}

func (e Direction) IsValid() bool {
	switch e {
	case DirectionIn, DirectionOut, DirectionInout:
		return true
	}
	return false
}

func (e Direction) String() string {
	return string(e)
}

func (e *Direction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Direction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Direction", str)
	}
	return nil
}

func (e Direction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Direction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Direction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
