package projection

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/Roarge/sysml-federation/adapter/model"
)

// SetAttribute is the resolver for the setAttribute field.
func (r *mutationResolver) SetAttribute(ctx context.Context, partID string, name string, value float64) (*model.Part, error) {
	p, m, err := r.Store.SetAttribute(partID, name, value)
	if err != nil {
		return nil, err
	}
	advance(ctx, m)
	return p, nil
}

// SetLimit is the resolver for the setLimit field.
func (r *mutationResolver) SetLimit(ctx context.Context, requirementID string, value float64) (*model.Requirement, error) {
	req, m, err := r.Store.SetLimit(requirementID, value)
	if err != nil {
		return nil, err
	}
	advance(ctx, m)
	return req, nil
}

// ResetModel is the resolver for the resetModel field.
func (r *mutationResolver) ResetModel(ctx context.Context) (*model.Model, error) {
	m := r.Store.Reset()
	advance(ctx, m)
	return m, nil
}

// Satisfies is the resolver for the satisfies field.
func (r *partResolver) Satisfies(ctx context.Context, obj *model.Part) ([]*model.Requirement, error) {
	return requirements(r.current(ctx), obj.Satisfies)
}

// Direction is the resolver for the direction field.
func (r *portResolver) Direction(ctx context.Context, obj *model.Port) (Direction, error) {
	return Direction(obj.Direction.String()), nil
}

// Model is the resolver for the model field.
func (r *queryResolver) Model(ctx context.Context) (*model.Model, error) {
	return r.current(ctx), nil
}

// Part is the resolver for the part field.
func (r *queryResolver) Part(ctx context.Context, id string) (*model.Part, error) {
	p, _ := partByID(r.current(ctx), id)
	return p, nil
}

// Requirement is the resolver for the requirement field.
func (r *queryResolver) Requirement(ctx context.Context, id string) (*model.Requirement, error) {
	req, _ := requirementByID(r.current(ctx), id)
	return req, nil
}

// Subject is the resolver for the subject field.
func (r *requirementResolver) Subject(ctx context.Context, obj *model.Requirement) (*model.Part, error) {
	if obj.Subject == "" {
		return nil, nil
	}
	p, ok := partByID(r.current(ctx), obj.Subject)
	if !ok {
		return nil, fmt.Errorf("%w: part %q", model.ErrNotFound, obj.Subject)
	}
	return p, nil
}

// Comparison is the resolver for the comparison field.
func (r *requirementResolver) Comparison(ctx context.Context, obj *model.Requirement) (*Comparison, error) {
	c := Comparison(obj.Comparison.String())
	return &c, nil
}

// DerivedFrom is the resolver for the derivedFrom field.
func (r *requirementResolver) DerivedFrom(ctx context.Context, obj *model.Requirement) ([]*model.Requirement, error) {
	return requirements(r.current(ctx), obj.DerivedFrom)
}

// Derives is the resolver for the derives field.
func (r *requirementResolver) Derives(ctx context.Context, obj *model.Requirement) ([]*model.Requirement, error) {
	return requirements(r.current(ctx), obj.Derives)
}

// SatisfiedBy is the resolver for the satisfiedBy field.
func (r *requirementResolver) SatisfiedBy(ctx context.Context, obj *model.Requirement) ([]*model.Part, error) {
	return parts(r.current(ctx), obj.SatisfiedBy)
}

// VerifiedBy is the resolver for the verifiedBy field.
func (r *requirementResolver) VerifiedBy(ctx context.Context, obj *model.Requirement) ([]*model.VerificationCase, error) {
	return verificationCases(r.current(ctx), obj.VerifiedBy)
}

// ModelChanged is the resolver for the modelChanged field.
func (r *subscriptionResolver) ModelChanged(ctx context.Context) (<-chan int, error) {
	return r.Store.Subscribe(ctx), nil
}

// Verifies is the resolver for the verifies field.
func (r *verificationCaseResolver) Verifies(ctx context.Context, obj *model.VerificationCase) ([]*model.Requirement, error) {
	return requirements(r.current(ctx), obj.Verifies)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Part returns PartResolver implementation.
func (r *Resolver) Part() PartResolver { return &partResolver{r} }

// Port returns PortResolver implementation.
func (r *Resolver) Port() PortResolver { return &portResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Requirement returns RequirementResolver implementation.
func (r *Resolver) Requirement() RequirementResolver { return &requirementResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// VerificationCase returns VerificationCaseResolver implementation.
func (r *Resolver) VerificationCase() VerificationCaseResolver { return &verificationCaseResolver{r} }

type (
	mutationResolver         struct{ *Resolver }
	partResolver             struct{ *Resolver }
	portResolver             struct{ *Resolver }
	queryResolver            struct{ *Resolver }
	requirementResolver      struct{ *Resolver }
	subscriptionResolver     struct{ *Resolver }
	verificationCaseResolver struct{ *Resolver }
)
