// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package document

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Document struct {
	Version int     `json:"version"`
	Nodes   []*Node `json:"nodes"`
}

type Mutation struct {
}

type Node struct {
	ID          string       `json:"id"`
	Kind        NodeKind     `json:"kind"`
	Number      *string      `json:"number,omitempty"`
	Text        *string      `json:"text,omitempty"`
	Requirement *Requirement `json:"requirement,omitempty"`
	Children    []*Node      `json:"children"`
}

type Query struct {
}

type Requirement struct {
	ID             string  `json:"id"`
	DocumentNumber *string `json:"documentNumber,omitempty"`
	Included       bool    `json:"included"`
}

func (Requirement) IsEntity() {}

type Subscription struct {
}

type NodeKind string

const (
	NodeKindHeading     NodeKind = "HEADING"
	NodeKindProse       NodeKind = "PROSE"
	NodeKindRequirement NodeKind = "REQUIREMENT"
)

var AllNodeKind = []NodeKind{
	NodeKindHeading,
	NodeKindProse,
	NodeKindRequirement,
}

func (e NodeKind) IsValid() bool {
	switch e {
	case NodeKindHeading, NodeKindProse, NodeKindRequirement:
		return true
	}
	return false
}

func (e NodeKind) String() string {
	return string(e)
}

func (e *NodeKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NodeKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NodeKind", str)
	}
	return nil
}

func (e NodeKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NodeKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NodeKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
