package document

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/Roarge/sysml-federation/examples/pipeline/document/tree"
)

// MoveNode is the resolver for the moveNode field.
func (r *mutationResolver) MoveNode(ctx context.Context, id string, parentID *string, index int) (*Document, error) {
	return r.service.apply(func(t *tree.Tree) error { return t.Move(id, deref(parentID), index) })
}

// InsertHeading is the resolver for the insertHeading field.
func (r *mutationResolver) InsertHeading(ctx context.Context, aboveID string, text string) (*Document, error) {
	return r.service.apply(func(t *tree.Tree) error { _, err := t.InsertHeading(aboveID, text); return err })
}

// AddProse is the resolver for the addProse field.
func (r *mutationResolver) AddProse(ctx context.Context, parentID *string, index int, text string) (*Document, error) {
	return r.service.apply(func(t *tree.Tree) error { _, err := t.AddProse(deref(parentID), index, text); return err })
}

// EditText is the resolver for the editText field.
func (r *mutationResolver) EditText(ctx context.Context, id string, text string) (*Document, error) {
	return r.service.apply(func(t *tree.Tree) error { return t.EditText(id, text) })
}

// ExcludeRequirement is the resolver for the excludeRequirement field.
func (r *mutationResolver) ExcludeRequirement(ctx context.Context, requirementID string) (*Document, error) {
	return r.service.apply(func(t *tree.Tree) error { return t.Exclude(requirementID) })
}

// IncludeRequirement is the resolver for the includeRequirement field.
func (r *mutationResolver) IncludeRequirement(ctx context.Context, requirementID string) (*Document, error) {
	return r.service.apply(func(t *tree.Tree) error { return t.Include(requirementID) })
}

// ResetDocument is the resolver for the resetDocument field.
func (r *mutationResolver) ResetDocument(ctx context.Context) (*Document, error) {
	return r.service.apply(r.service.reset)
}

// Document is the resolver for the document field.
func (r *queryResolver) Document(ctx context.Context) (*Document, error) {
	return r.service.document(), nil
}

// DocumentChanged is the resolver for the documentChanged field.
func (r *subscriptionResolver) DocumentChanged(ctx context.Context) (<-chan int, error) {
	return r.service.subscribe(ctx), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
